# This is the build workflow that will run the script file 

name: build
on: push

jobs:
  run:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v1
    - name: script
    - run: |
      # make file runnable, might not be necessary
      chmod +x "${GITHUB_WORKSPACE}/.github/build.sh"
      # run script
      "${GITHUB_WORKSPACE}/.github/build.sh"
      # or
      "${{ format('{0}/.github/build.sh', github.workspace) }}"
      shell: bash
      with:
      password: ${{ secrets.ACCESS_TOKEN }}
